replicaCount: 1

image:
  repository: ghcr.io/thuongh2/hoaithuong-portfolio
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: traefik
  annotations: {}
  hosts:
    - host: portfolio.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 128Mi
